---
name: node_util
permissions:
  contents: read
  id-token: write

on:
  push:
    branches:
      - main
      - 'feat-**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Assign AWS PROD role to get access to production cloudfronts and S3 buckets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ACCESS_ROLE_GENESIS }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ secrets.AWS_ACCESS_REGION_GENESIS }}

      - name: Make useless file
        run: |
          echo "test file" >> upload-file

      - name: Upload artifacts to S3
        run: |
          aws s3 sync . s3://${{ secrets.AWS_BUCKET_GENESIS }}/artifact/node-util/

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_GENESIS }} --paths "/artifact/node-util/*"
